USE `sentiment_pf`;

ALTER TABLE `figure` ADD `category` VARCHAR(50);
ALTER TABLE `figure` ADD `access` INTEGER DEFAULT 0;

DELETE FROM `sentiment`;

REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('1','ariana grande','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('2','avicii','DJ');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('3','angelina jolie','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('4','albert enstein','Scientist');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('5','anya taylor-joy','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('6','amber heard','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('7','aaron rodgers','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('8','angela merkel','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('9','anthony joshua','Boxer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('10','abraham lincoln','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('11','andy murray','actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('12','audrey hepburn','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('13','alfred molina','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('14','adam sandler','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('15','asa butterfiled','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('16','anne hathaway','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('17','adam driver','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('18','adam peaty','Swimmer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('19','antoine griezmann','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('20','andrew garfield','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('21','alexandria ocasio-cortez','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('22','avril lavigne','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('23','amitabh bachchan','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('24','alan turing','Scientist');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('25','adele','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('26','alex ferguson','Coach');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('27','andy warhol','Artist');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('28','agatha christie','Writer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('29','adam levine','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('30','axl rose','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('31','alvaro morata','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('32','angel di maria','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('33','asap rocky','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('34','alex antetokounmpo','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('35','anthony mackie','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('36','andres iniesta','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('37','allen iverson','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('38','antonio conte','Coach');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('39','anthony martial','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('40','anthony davis','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('41','andrea pirlo','Coach');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('42','ben affleck','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('43','billie ellish','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('44','barack obama','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('45','brendan fraser','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('46','bob ross','Artist');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('47','bruce lee','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('48','bradd pitt','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('49','boris johnson','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('50','billie cosby','Comedian');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('51','beyonce','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('52','bill gates','Billionaire');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('53','bill clinton','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('54','bnedict cumberbatch','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('55','bruno mars','Musician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('56','brie larson','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('57','bella hadid','Model');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('58','blake griffin','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('59','ben stiller','actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('60','ben simmons','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('61','brook lopez','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('62','brian ortega','Murcle Art');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('63','big show','Wrestler');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('64','bad bunny','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('65','bebe rexha','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('66','bae suzy','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('67','cristiano ronaldo','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('68','conor mcgregor','Professional Fighter');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('69','chris pratt','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('70','camila cabello','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('71','chadwick boseman','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('72','chris hemsworth','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('73','chris paul','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('74','cillian murphy','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('75','chris evans','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('76','cardi b','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('77','cameron diaz','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('78','courteney cox','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('79','christopher nolan','Producer Film');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('80','carrie fisher','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('81','chris martin','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('82','chloe grace moretz','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('83','cara delevingne','Model');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('84','carmelo anthony','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('85','celine dion','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('86','chris brown','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('87','coco gauff','Tennis Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('88','christian eriksen','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('89','charles barkley','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('90','charlie puth','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('91','dwayne johnson','Wrestler');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('92','donald trump','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('93','dua lipa','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('94','daniel craig','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('95','doja cat','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('96','drake','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('97','devin booker','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('98','david beckham','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('99','david bowie','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('100','daniel radcliffe','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('101','dakota johnson','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('102','demi lovato','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('103','diego maradona','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('104','dave grohl','Musician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('105','david schwimmer','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('106','dennis rodman','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('107','donald glover','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('108','dwayne wade','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('109','elon musk','Billionaire');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('110','emily blunt','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('111','eminem','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('112','ed sheeran','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('113','elliot page','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('114','emma watson','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('115','emma stone','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('116','ernest hemingway','Writer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('117','elizabeth olson','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('118','eric clapton','Musician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('119','emma mackey','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('120','edward snowden','Intellegent Consultant');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('121','edison cavani','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('122','freddie mercury','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('123','floyd mayweather jr.','Boxer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('124','frank ocean','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('125','giannis antetokounmpo','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('126','george w. bush','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('127','gigi hadid','Model');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('128','gordon ramsey','Chef');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('129','gemma chan','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('130','gal gadot','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('131','george clooney','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('132','gerard pique','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('133','greta thunberg','Activist');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('134','gong yoo','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('135','guy fieri','Entrepreneur');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('136','gerard way','Musician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('137','harry kane','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('138','halsey','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('139','harry styles','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('140','harrsion ford','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('141','henry cavill','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('142','hugh jackman','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('143','hillary clinton','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('144','hanz zimmer','Producer Film');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('145','jeff bezos','Billionaire');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('146','joe biden','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('147','jason momoa','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('148','jennifer lopez','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('149','john cena','Wrestler');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('150','jennifer aniston','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('151','johnny depp','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('152','justin bieber','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('153','jake paul','Boxer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('154','jackie chan','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('155','julia roberts','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('156','joaquin phoenix','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('157','jim carrey','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('158','jay z','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('159','james franco','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('160','jack black','Producer Film');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('161','j. k. rowling','Writer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('162','jared leto','Singer/Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('163','Kanye west','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('164','keanu reeves','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('165','kim kardashian','Model');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('166','kylie jenner','Model');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('167','khabib nurmagomedov','Fighter');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('168','kobe bryant','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('169','kristen stewart','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('170','kylian mbappe','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('171','kurt cobain','Musician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('172','kamala harris','Politician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('173','kevin durant','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('174','kendall jenner','Model');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('175','kevin hart','Comedian');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('176','katy perry','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('177','lionnel messi','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('178','lebron james','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('179','lewis hamilton','Professional Racer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('180','lady gaga','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('181','lorde','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('182','lisa blackpink','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('183','luke shaw','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('184','lonzo ball','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('185','lamelo ball','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('186','lindsay lohan','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('187','luis suarez','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('188','lana del ray','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('189','lisa kudrow','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('190','lucy liu','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('191','liam gallagher','Musician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('192','michael phelps','Swimmer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('193','muhammad ali','Boxer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('194','mark zuckerberg','Billionaire');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('195','michael jackson','Musician');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('196','michael jordan','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('197','megan fox','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('198','margot robbie','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('199','mike tayson','Boxer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('200','mick jagger','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('201','megan rapinoe','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('202','naomi osaka','Tennis Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('203','nora lum','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('204','neymar jr.','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('205','nicki minaj','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('206','neil patrick harris','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('207','olivia rodrigo','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('208','owen wilson','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('209','oprah winfrey','Entrepreneur');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('210','priyanka chopra','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('211','paris hilton','Model');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('212','paul rudd','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('213','prince william','Prince of Britain');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('214','paul pogba','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('215','post malone','Rapper');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('216','ryan renolds','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('217','rihanna','Singer');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('218','rafael nadal','Tennis Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('219','robert pattinson','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('220','rami malek','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('221','rowen atkinson','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('222','simu liu','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('223','steve jobs','Billionaire');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('224','selena gomes','Singer/Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('225','shohei ohtani','Football Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('226','salma hayek','Actress');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('227','sue bird','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('228','zach lavine','Basketball Player');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('229','tom holland','Actor');
REPLACE INTO `figure` (`id`, `name`, `category`) VALUES('230','taylor swift','Singer');
